#!/bin/bash

set -e -o pipefail

echo "$0: check for ST-LINK programmer"
st-info --chipid

echo "$0: format external flash"
scripts/format-external

echo "$0: erase SRAM and internal flash"
st-flash erase
